apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netboot-xyz
  namespace: netboot-xyz
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: netboot-xyz
  values:
    image:
      repository: ghcr.io/h3mul/netboot-xyz
      tag: 3.0.0@sha256:b2dca4e6a4d1e583d6274084781b21acffa34e7789c625a5b6f67722cc7a5f07

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: &host "netboot.${CLUSTER_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: letsencrypt-wildcard-cert-prod
          hosts:
          - *host
