---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescale-cluster
  namespace: cloudnative-pg
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 18
  imagePullPolicy: IfNotPresent
  postgresUID: 70
  postgresGID: 70

  postgresql:
    shared_preload_libraries:
      - timescaledb
  
  storage:
    size: 20Gi
    storageClass: truenas-ssd-iscsi
    
  monitoring:
    enablePodMonitor: true
  
  enableSuperuserAccess: true
  superuserSecret:
    name: timescale-cluster-superuser

  managed:
    services:
      additional:
        - selectorType: "rw"
          serviceTemplate:
            metadata:
              name: timescale-cluster-rw-external
              annotations:
                external-dns.alpha.kubernetes.io/hostname: timescale.${CLUSTER_DOMAIN}
                cilium.io/bgp-advertisement-mode: "local"
                # Force SNAT mode specifically for this L4 service (overrides DSR/BGP state issues)
                service.cilium.io/lb-l4-mode: "snat"
            spec:
              type: LoadBalancer
              externalTrafficPolicy: Local
              
---

apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
  namespace: cloudnative-pg
spec:
  images:
    - major: 18
      image: timescale/timescaledb:2.29.1-pg18@sha256:373eb0fee9c0f8e0b4b0d4e74c7d0dd463dce05de6b49982701c4b540e94cba0
