apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: ghost
  values:
    controllers:
      ghost:
        containers:
          main:
            image:
              repository: ghost
              tag: 
                6.26.0@sha256:5130e5a9ea4f91f4131d7ca95e254dd8fdc406ef6b5ac11d18a543d947f35cb3
            env:
              TZ: ${TIMEZONE}
              url: "https://ghost.${CLUSTER_DOMAIN}"
              database__client: sqlite3
              database__connection__filename: /var/lib/ghost/content/data/ghost.db
              NODE_ENV: production

        # initContainers:
        #   init-db:
        #     image: ghcr.io/h3mul/mysql-init:11.4.2@sha256:9826276e6134c391059343acb2b0762581a8d756d7c089db39513a5fc753d4a9
        #     imagePullPolicy: IfNotPresent
        #     env:
        #       - name: INIT_MYSQL_HOST
        #         value: main-mysql.mysql-operator.svc.cluster.local
        #       - name: INIT_MYSQL_SUPER_USER
        #         value: root
        #       - name: INIT_MYSQL_SUPER_PASS
        #         valueFrom:
        #           secretKeyRef:
        #             name: mysql-main
        #             key: ROOT_PASSWORD
        #       - name: INIT_MYSQL_DBNAME
        #         valueFrom:
        #           secretKeyRef:
        #             name: ghost-mysql-credentials
        #             key: MYSQL_DBNAME
        #       - name: INIT_MYSQL_USER
        #         valueFrom:
        #           secretKeyRef:
        #             name: ghost-mysql-credentials
        #             key: MYSQL_USER
        #       - name: INIT_MYSQL_PASS
        #         valueFrom:
        #           secretKeyRef:
        #             name: ghost-mysql-credentials
        #             key: MYSQL_PASS

    service:
      app:
        controller: ghost
        ports:
          http:
            port: 2368

    ingress:
      app:
        className: nginx
        hosts:
          - host: &host ghost.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: letsencrypt-wildcard-cert-prod
            hosts:
              - *host

    persistence:
      content:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-ssd-iscsi
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /var/lib/ghost/content
