apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost
resources:
 - kustomization-ghost-config-restic.yaml
 - replication-source-ghost-config.yaml
 - helmrelease-ghost.yaml
 # - sealed-secret-ghost-mysql-credentials.yaml
