apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
  namespace: penpot
spec:
  chart:
    spec:
      chart: penpot
      version: 0.38.0
      sourceRef:
        kind: HelmRepository
        name: penpot
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: penpot
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: penpot-backend
            patch: |
              - op: add
                path: /spec/template/spec/initContainers
                value:
                  - name: init-db
                    image: ghcr.io/home-operations/postgres-init:17.5.0
                    env:
                      - name: INIT_POSTGRES_HOST
                        value: postgres-cluster-rw.cloudnative-pg.svc.cluster.local
                      - name: INIT_POSTGRES_SUPER_USER
                        valueFrom:
                          secretKeyRef:
                            name: postgres-cluster-superuser
                            key: username
                      - name: INIT_POSTGRES_SUPER_PASS
                        valueFrom:
                          secretKeyRef:
                            name: postgres-cluster-superuser
                            key: password
                      - name: INIT_POSTGRES_DBNAME
                        valueFrom:
                          secretKeyRef:
                            name: penpot-postgres-credentials
                            key: POSTGRES_DB
                      - name: INIT_POSTGRES_USER
                        valueFrom:
                          secretKeyRef:
                            name: penpot-postgres-credentials
                            key: POSTGRES_USER
                      - name: INIT_POSTGRES_PASS
                        valueFrom:
                          secretKeyRef:
                            name: penpot-postgres-credentials
                            key: POSTGRES_PASS

  valuesFrom:
  - kind: Secret
    name: penpot-postgres-credentials
    valuesKey: POSTGRES_DB
    targetPath: config.postgresql.database

  values:
    # Values:
    # https://github.com/penpot/penpot-helm/blob/2d736b77cc53e2db89bde678b0890e99f1fc779c/charts/penpot/values.yaml

    global:
      postgresqlEnabled: false
      redisEnabled: false
      valkeyEnabled: true

    config:
      # -- The public domain to serve Penpot on.
      # **IMPORTANT:** Set `disable-secure-session-cookies` in the flags if you plan on serving it on a non HTTPS domain.
      # @section -- Configuration parameters
      publicUri: "https://penpot.${CLUSTER_DOMAIN}"
      # -- The feature flags to enable. Check [the official docs](https://help.penpot.app/technical-guide/configuration/) for more info.
      # @section -- Configuration parameters
      flags: "enable-registration enable-login-with-password disable-email-verification disable-smtp disable-secure-session-cookies"
      # -- A random secret key needed for persistent user sessions. Generate with `python3 -c "import secrets; print(secrets.token_urlsafe(64))"` for example.
      # @section -- Configuration parameters
      # apiSecretKey: "kmZ96pAxhTgk3HZvvBkPeVTspGBneKVLEpO_3ecORs_gwACENZ77z05zCe7skvPsQ3jI3QgkULQOWCuLjmjQsg"
      # -- Comma separated list of allowed domains to register. Empty to allow all domains.
      # @section -- Configuration parameters
      registrationDomainWhitelist: ""
      # -- Whether to enable sending of anonymous telemetry data.
      # @section -- Configuration parameters
      telemetryEnabled: false
      # -- Add custom resolver for frontend. e.g. 192.168.1.1
      # @section -- Configuration parameters
      internalResolver: ""

      postgresql:
        # -- The PostgreSQL host to connect to. Empty to use dependencies.
        # @section -- Configuration parameters
        host: "postgres-cluster-rw.cloudnative-pg.svc.cluster.local"  # Ex.: "postgresql.penpot.svc.cluster.local"
        # -- The PostgreSQL host port to use.
        # @section -- Configuration parameters
        port: 5432
        # -- The database username to use.
        # @section -- Configuration parameters
        # username: "penpot"
        # -- The database password to use.
        # @section -- Configuration parameters
        # password: "penpot"
        # -- The PostgreSQL database to use.
        # @section -- Configuration parameters
        # database: "penpot"
        # -- The name of an existing secret.
        # @section -- Configuration parameters
        existingSecret: "penpot-postgres-credentials"
        secretKeys:
          # -- The username key to use from an existing secret.
          # @section -- Configuration parameters
          usernameKey: "POSTGRES_USER"
          # -- The password key to use from an existing secret.
          # @section -- Configuration parameters
          passwordKey: "POSTGRES_PASS"

      redis:
        # -- The Redis host to connect to. Empty to use dependencies
        # @section -- Configuration parameters
        host: penpot-valkey-primary
        # -- The Redis host port to use.
        # @section -- Configuration parameters
        port: 6379
        # -- The Redis database to connect to.
        # @section -- Configuration parameters
        database: "0"
        
    frontend:
      replicaCount: 1
  
    exporter:
      replicaCount: 1   

    persistence:
      assets:
        enabled: true
        storageClass: truenas-ssd-nfs
        accessModes:
          - ReadWriteMany
          
      exporter:
        enabled: true
        storageClass: truenas-ssd-nfs
        accessModes:
          - ReadWriteMany

    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
      hosts:
        - &host penpot.${CLUSTER_DOMAIN}
      tls:
      - secretName: letsencrypt-wildcard-cert-prod
        hosts:
        - *host
