apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dunkbot
  namespace: red-discord-bot
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: dunkbot
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: phasecorex/red-discordbot
              tag: full@sha256:534fe17e83ee35f396bbb2092a69e2983a2f3e67a22567d1d3483b6d7be76ec9
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}
              PREFIX: "!"

            envFrom:
              - secretRef:
                  name: dunkbot-discord-token

    persistence:
      data:
        enabled: true
        existingClaim: dunkbot-data
        globalMounts:
          - path: /data