apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dunkbot
  namespace: red-discord-bot
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: dunkbot
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: phasecorex/red-discordbot
              tag: full@sha256:e3cc8fc4f690c8aaa47da36b74dcef9cf014e67fa044b5bdebeb1f68b39fad81
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}
              PREFIX: "!"

            envFrom:
              - secretRef:
                  name: dunkbot-discord-token

    persistence:
      data:
        enabled: true
        existingClaim: dunkbot-data
        globalMounts:
          - path: /data