apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dunkbot
  namespace: red-discord-bot
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: dunkbot
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: phasecorex/red-discordbot
              tag: full@sha256:a8845d5041bee052819de9588ece474148ca9c2736fffdec019c61bd68f77f46
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}
              PREFIX: "!"

            envFrom:
              - secretRef:
                  name: dunkbot-discord-token

    persistence:
      data:
        enabled: true
        existingClaim: dunkbot-data
        globalMounts:
          - path: /data