apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployment
  namespace: democratic-csi
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '0 */6 * * *' # Every 6h
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-deployment
          restartPolicy: Never
          containers:
            - name: restart-iscsi-deployment
              image: bitnami/kubectl@sha256:d80c09afa570a14cf6d32ca09ca610b5701eb0a08c655b5bb820194b218078eb 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/democratic-csi-ssd-iscsi-controller'
            - name: restart-nfs-deployment
              image: bitnami/kubectl@sha256:d80c09afa570a14cf6d32ca09ca610b5701eb0a08c655b5bb820194b218078eb 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/democratic-csi-ssd-nfs-controller'