apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployment
  namespace: democratic-csi
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '0 */6 * * *' # Every 6h
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-deployment
          restartPolicy: Never
          containers:
            - name: restart-iscsi-deployment
              image: bitnami/kubectl@sha256:b9f4412e53f09d76b0991cdd29c0feff4c1d1e112b307e0ab155e5b050a9f4ec 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/democratic-csi-ssd-iscsi-controller'
            - name: restart-nfs-deployment
              image: bitnami/kubectl@sha256:b9f4412e53f09d76b0991cdd29c0feff4c1d1e112b307e0ab155e5b050a9f4ec 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/democratic-csi-ssd-nfs-controller'