apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: grafana
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.${CLUSTER_DOMAIN}
      tls:
        - secretName: letsencrypt-wildcard-cert-prod
          hosts:
            - grafana.${CLUSTER_DOMAIN}

    admin:
      existingSecret: grafana-credentials

    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
      - savantly-heatmap-panel
      
    envValueFrom:
      BRAINLESS_DB_PASSWORD:
        secretKeyRef:
          name: brainless-timescale-db-credentials
          key: password
          
      BRAINLESS_DB_USER:
        secretKeyRef:
          name: brainless-timescale-db-credentials
          key: user
          
      BRAINLESS_DB_NAME:
        secretKeyRef:
          name: brainless-timescale-db-credentials
          key: database
          
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
            
          - name: Loki
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local:80
            access: proxy
            
          - name: BrainLess Timescale
            type: postgres
            access: proxy
            url: timescale-cluster-r.cloudnative-pg.svc.cluster.local:5432
            user: "$__env{BRAINLESS_DB_USER}"
            database: "$__env{BRAINLESS_DB_NAME}"
            jsonData:
              sslmode: disable
              timescaledb: true
              postgresVersion: 1500
            secureJsonData:
              password: "$__env{BRAINLESS_DB_PASSWORD}"

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        opnsense:
          gnetId: 19366
          revision: 2
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
              
        qbittorrent:
          url: https://raw.githubusercontent.com/esanchezm/prometheus-qbittorrent-exporter/master/grafana/dashboard.json
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
              
        blocky:
          gnetId: 13768
          revision: 3
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
              
        node-exporter-full:
          gnetId: 1860
          revision: 30
          datasource: Prometheus
          
        gitea:
          gnetId: 13192
          revision: 1
          datasource: Prometheus
          
        speedtest-exporter:
          gnetId: 13665
          revision: 4
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
              
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/cluster.json
          datasource: Prometheus
          
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/control-plane.json
          datasource: Prometheus
          
        kubernetes-api-server:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
          datasource: Prometheus
          
        kubernetes-coredns:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
          datasource: Prometheus
          
        kubernetes-global:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
          datasource: Prometheus
          
        kubernetes-namespaces:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
          datasource: Prometheus
          
        kubernetes-nodes:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
          datasource: Prometheus
          
        kubernetes-pods:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
          datasource: Prometheus
          
        cloudnative-pg:
          url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/grafana-dashboard.json
          datasource: Prometheus

    # grafana.ini:
    #   grafana_net:
    #     url: https://grafana.net
    #   server:
    #     domain: grafana.${CLUSTER_DOMAIN}
    #     root_url: grafana.${CLUSTER_DOMAIN}
