apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: prowlarr
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.6.3@sha256:8c9ee448bb6de0e3e8b9c2f536b7a3455ec6ff5e184c2fb2a8602791b2757442
            env:
              TZ: ${TIMEZONE}
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__THEME: dark
              PROWLARR__SERVER__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-api-key
                    key: api_key
        pod:
          hostname: prowlarr
          securityContext:
            runAsUser: ${FILESHARE_USER_ID}
            runAsGroup: ${FILESHARE_GROUP_ID}
            fsGroup: ${FILESHARE_GROUP_ID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539

    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${CLUSTER_DOMAIN}/css/base/prowlarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host prowlarr.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: letsencrypt-wildcard-cert-prod
            hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: truenas-ssd-iscsi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config
