apiVersion: batch/v1
kind: Job
metadata:
  name: cmd-volume
  namespace: ${namespace}

spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: volume-cmd
        image: alpine@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
        imagePullPolicy: IfNotPresent

        command: [ "/bin/sh" ]
        args:
          - -c
          - ${command}

        volumeMounts:
          - name: volume
            mountPath: /volume

      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: ${volume}
